title: Raja Shekar
logo: '/assets/headshot.jpg'
description: >
  <a href="https://www.linkedin.com/in/raja-shekar/">View my LinkedIn Profile</a> 
  <br>Versatile and results-driven Software Engineer, acknowledged for orchestrating groundbreaking advancements in Mine Digitization and Automation Platforms. My 2.5+ years of expertise have fueled a substantial 40% increase in mining efficiency per shift.<br>
  <br><br>
  Currently charting a dynamic career shift toward data science, pursuing an MSc in Data Science and Analytics at the University of Hertfordshire.
show_downloads: false
theme: jekyll-remote-theme
