title: Raja Shekar
logo: "/images/headshot.png?raw=true"
description: >
  <p align="center">
    <a href="https://www.linkedin.com/in/raja-shekar/">View my LinkedIn Profile</a> 
    <br>MSc Data Science Student<br>
    <br><br>
  </p>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
google_analytics: G-TH5VEMBXCG
resume_link: 'https://drive.google.com/file/d/11tySshJdglvefRWU4mjejyl-xrmzdrUE/view?usp=sharing'