title: Raja Shekar
logo: "/images/headshot.png?raw=true"
description: >
  <a href="https://www.linkedin.com/in/raja-shekar/">View my LinkedIn Profile</a> 
  <br>Mean Stack Developer Turned Data Science Enthusiast | MSc Data Science Student<br>
  <br><br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
google_analytics: G-TH5VEMBXCG
resume_link: 'https://drive.google.com/file/d/11qakiz9EFCHO5gnRkuBAn7mGLOpVoB5i/view?usp=sharing'
