title: Raja Shekar
logo: '/assets/headshot.jpg'
description: >
  <a href="https://www.linkedin.com/in/raja-shekar/">View my LinkedIn Profile</a> 
  <br>Mean Stack Developer Turned Data Science Enthusiast | MSc Data Science Student<br>
  <br><br>
show_downloads: false
theme: jekyll-theme-minimal
